import { ssrRenderAttrs, ssrRenderAttr } from "vue/server-renderer";
import { _ as _imports_0 } from "./post-payment-process.5iOIx7dp.js";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"ادفع فقط بعد النجاح - لا رسوم وكيل مقدماً","description":"على عكس الآخرين، نحن نفرض فقط الرسوم الحكومية مقدماً ورسوم خدماتنا بعد الموافقة. لا مخاطر، شفافية كاملة، ونتائج مضمونة.","frontmatter":{"title":"ادفع فقط بعد النجاح - لا رسوم وكيل مقدماً","description":"على عكس الآخرين، نحن نفرض فقط الرسوم الحكومية مقدماً ورسوم خدماتنا بعد الموافقة. لا مخاطر، شفافية كاملة، ونتائج مضمونة.","head":[["meta",{"name":"robots","content":"noindex"}]],"dir":"rtl"},"headers":[],"params":{},"relativePath":"ar/uae-business/benefits/success-based-fees.md","filePath":"i18n/ar/uae-business/benefits/success-based-fees.md","lastUpdated":1743504341000}');
const _sfc_main = { name: "ar/uae-business/benefits/success-based-fees.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="ادفع-فقط-بعد-النجاح-لا-رسوم-وكيل-مقدماً" tabindex="-1">ادفع فقط بعد النجاح - لا رسوم وكيل مقدماً <a class="header-anchor" href="#ادفع-فقط-بعد-النجاح-لا-رسوم-وكيل-مقدماً" aria-label="Permalink to &quot;ادفع فقط بعد النجاح - لا رسوم وكيل مقدماً&quot;">​</a></h1><h2 id="نهجنا-الفريد-في-الدفع" tabindex="-1">نهجنا الفريد في الدفع <a class="header-anchor" href="#نهجنا-الفريد-في-الدفع" aria-label="Permalink to &quot;نهجنا الفريد في الدفع&quot;">​</a></h2><p>في عالم خدمات الأعمال وإجراءات الهجرة في الإمارات العربية المتحدة، تطلب معظم الشركات دفع كامل المبلغ مقدماً، بما في ذلك الرسوم الحكومية ورسوم الوكيل. يعدون برد رسوم الوكيل فقط في حالة الرفض، بينما الرسوم الحكومية غير قابلة للاسترداد.</p><h2 id="ما-يميزنا-عن-غيرنا" tabindex="-1">ما يميزنا عن غيرنا <a class="header-anchor" href="#ما-يميزنا-عن-غيرنا" aria-label="Permalink to &quot;ما يميزنا عن غيرنا&quot;">​</a></h2><p>نموذج أعمالنا مختلف جذرياً عن الممارسات المعتادة في السوق:</p><ol><li><p><strong>الرسوم الحكومية فقط مقدماً</strong> - نطلب من العملاء فقط دفع الرسوم الحكومية الإلزامية اللازمة لبدء العملية</p></li><li><p><strong>رسوم خدماتنا بعد الموافقة فقط</strong> - نقوم بإصدار فاتورة خدماتنا المهنية فقط بعد الحصول على قرار إيجابي</p></li><li><p><strong>لا مخاطر لفقدان الأموال</strong> - لن تخسر أموالك على عمولات الوكلاء في حالة الرفض</p></li></ol><h2 id="مزايا-نهجنا" tabindex="-1">مزايا نهجنا <a class="header-anchor" href="#مزايا-نهجنا" aria-label="Permalink to &quot;مزايا نهجنا&quot;">​</a></h2><ul><li><strong>استثمار أولي بسيط</strong> - لا حاجة لدفع مبالغ كبيرة مقدماً</li><li><strong>عبء مالي موزع</strong> - ادفع الجزء الرئيسي فقط عندما تكون النتائج مضمونة</li><li><strong>شفافية كاملة</strong> - فصل واضح بين الرسوم الحكومية وخدماتنا</li><li><strong>ثقة في الجودة</strong> - نحن واثقون جداً من نجاحنا لدرجة أننا على استعداد للانتظار حتى تحقيق النتائج للحصول على المدفوعات</li></ul><h2 id="كيف-تتم-العملية" tabindex="-1">كيف تتم العملية <a class="header-anchor" href="#كيف-تتم-العملية" aria-label="Permalink to &quot;كيف تتم العملية&quot;">​</a></h2><ol><li>استشارة أولية (مجانية)</li><li>دفع الرسوم الحكومية فقط</li><li>نتولى جميع أعمال إعداد وتقديم المستندات</li><li>بعد الموافقة، تستلم فاتورة خدماتنا</li><li>إتمام العملية واستلام المستندات اللازمة</li></ol><p><img${ssrRenderAttr("src", _imports_0)} alt="عرض عملية الإعداد"></p><h2 id="لماذا-يمكننا-تقديم-هذه-الخدمة" tabindex="-1">لماذا يمكننا تقديم هذه الخدمة <a class="header-anchor" href="#لماذا-يمكننا-تقديم-هذه-الخدمة" aria-label="Permalink to &quot;لماذا يمكننا تقديم هذه الخدمة&quot;">​</a></h2><p>يتيح لنا مستوى خبرتنا العالي وسنوات خبرتنا الطويلة تقديم خدمات بأقل مخاطر للعملاء. نحن واثقون جداً من جودة خدماتنا لدرجة أننا على استعداد لتلقي التعويض فقط بعد تحقيق النتائج الناجحة.</p><p>تواصل معنا اليوم للحصول على استشارة مجانية واكتشف كيف يمكن أن يعمل نهجنا &quot;الدفع بعد الموافقة&quot; خصيصاً لحالتك.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("i18n/ar/uae-business/benefits/success-based-fees.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const successBasedFees = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  successBasedFees as default
};
