import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"यूएई में व्यवसाय स्थापना और विकास को सरल बनाना","description":"","frontmatter":{"head":[["meta",{"name":"robots","content":"noindex"}]]},"headers":[],"params":{},"relativePath":"hi/resources/about.md","filePath":"i18n/hi/resources/about.md","lastUpdated":1742883140000}');
const _sfc_main = { name: "hi/resources/about.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="यूएई-में-व्यवसाय-स्थापना-और-विकास-को-सरल-बनाना" tabindex="-1">यूएई में व्यवसाय स्थापना और विकास को सरल बनाना <a class="header-anchor" href="#यूएई-में-व्यवसाय-स्थापना-और-विकास-को-सरल-बनाना" aria-label="Permalink to &quot;यूएई में व्यवसाय स्थापना और विकास को सरल बनाना&quot;">​</a></h1><p>GOLDEN FISH यूएई में अपनी उपस्थिति स्थापित करने या विस्तार करने के इच्छुक व्यवसायों और पेशेवरों के लिए व्यापक समर्थन प्रदान करता है। हमारा मिशन स्थानांतरण, अनुपालन, व्यवसाय परामर्श और निरंतर प्रबंधन की जटिल प्रक्रियाओं को सरल बनाना है, जो हमारे ग्राहकों के लिए एक सुचारू और कुशल अनुभव सुनिश्चित करता है।</p><div class="info custom-block github-alert"><p class="custom-block-title">हमारी दृष्टि</p><p>विशेषज्ञ मार्गदर्शन और विश्वसनीय समर्थन प्रदान करके यूएई में सफल उपस्थिति स्थापित करने के इच्छुक व्यवसायों और पेशेवरों के लिए एक विश्वसनीय साझेदार बनना।</p></div><div class="info custom-block github-alert"><p class="custom-block-title">हमारा मिशन</p><p>स्थानांतरण और व्यवसाय स्थापना की प्रक्रिया को सरल बनाना, जो हमारे ग्राहकों को विकास और सफलता पर ध्यान केंद्रित करने में सक्षम बनाता है।</p></div><h3 id="कंपनी-रणनीति" tabindex="-1">कंपनी रणनीति <a class="header-anchor" href="#कंपनी-रणनीति" aria-label="Permalink to &quot;कंपनी रणनीति&quot;">​</a></h3><ul><li><strong>ग्राहक-केंद्रित दृष्टिकोण</strong>: हम प्रत्येक ग्राहक की विशिष्ट आवश्यकताओं और लक्ष्यों के अनुरूप अनुकूलित समाधान प्रदान करते हैं, जो सुचारू व्यवसाय परिवर्तन सुनिश्चित करता है।</li><li><strong>परिचालन उत्कृष्टता</strong>: स्थानीय विशेषज्ञता और कुशल प्रक्रियाओं का लाभ उठाकर, हम ग्राहकों को यूएई व्यवसाय वातावरण की जटिलताओं को नेविगेट करने में मदद करते हैं, जिससे समय और प्रयास कम होता है।</li><li><strong>स्थायी विकास</strong>: हम सतत, उच्च-गुणवत्ता वाली सेवाएं प्रदान करके अपने ग्राहकों के साथ दीर्घकालिक संबंध बनाने पर ध्यान केंद्रित करते हैं जो सफलता और विकास को बढ़ावा देती हैं।</li></ul><h3 id="हमारी-सेवाएं" tabindex="-1">हमारी सेवाएं <a class="header-anchor" href="#हमारी-सेवाएं" aria-label="Permalink to &quot;हमारी सेवाएं&quot;">​</a></h3><ul><li><strong>व्यवसाय स्थानांतरण</strong>: यूएई में अपना व्यवसाय स्थापित करने में विशेषज्ञ सहायता।</li><li><strong>परामर्श</strong>: आवश्यक दस्तावेजों को प्राप्त करने के लिए पेशेवर समर्थन।</li><li><strong>व्यवसाय समर्थन</strong>: आपके व्यवसाय को सफल होने और विकसित होने में मदद करने के लिए निरंतर परिचालन सहायता।</li></ul><div class="important custom-block github-alert"><p class="custom-block-title">हमें क्यों चुनें?</p><p>ज्ञानवान पेशेवरों की टीम और व्यक्तिगत सेवाओं के प्रति प्रतिबद्धता के साथ, हम ग्राहकों के लिए एक सुचारू और कुशल अनुभव सुनिश्चित करते हैं, जो उन्हें सबसे महत्वपूर्ण चीज पर ध्यान केंद्रित करने की अनुमति देता है – यूएई में अपने व्यवसाय को बढ़ाना।</p></div><hr><p><strong>अनास्तासिया खुर्तिना</strong><br> निदेशक</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("i18n/hi/resources/about.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const about = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  about as default
};
