import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"متحدہ عرب امارات میں کاروباری قیام اور ترقی کو آسان بنانا","description":"","frontmatter":{"head":[["meta",{"name":"robots","content":"noindex"}]],"dir":"rtl"},"headers":[],"params":{},"relativePath":"ur/resources/about.md","filePath":"i18n/ur/resources/about.md","lastUpdated":1742883140000}');
const _sfc_main = { name: "ur/resources/about.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="متحدہ-عرب-امارات-میں-کاروباری-قیام-اور-ترقی-کو-آسان-بنانا" tabindex="-1">متحدہ عرب امارات میں کاروباری قیام اور ترقی کو آسان بنانا <a class="header-anchor" href="#متحدہ-عرب-امارات-میں-کاروباری-قیام-اور-ترقی-کو-آسان-بنانا" aria-label="Permalink to &quot;متحدہ عرب امارات میں کاروباری قیام اور ترقی کو آسان بنانا&quot;">​</a></h1><p>GOLDEN FISH متحدہ عرب امارات میں اپنی موجودگی قائم کرنے یا بڑھانے کے خواہشمند کاروباری اداروں اور پیشہ ور افراد کے لیے جامع معاونت فراہم کرتا ہے۔ ہماری مہم منتقلی، قانونی تعمیل، کاروباری مشاورت، اور جاری انتظام کے پیچیدہ عمل کو آسان بنانا ہے، جو ہمارے کلائنٹس کے لیے ہموار اور موثر تجربہ یقینی بناتا ہے۔</p><div class="info custom-block github-alert"><p class="custom-block-title">ہمارا وژن</p><p>متحدہ عرب امارات میں ماہرانہ رہنمائی اور قابل اعتماد معاونت فراہم کرکے کامیاب موجودگی قائم کرنے کے خواہشمند کاروباری اداروں اور پیشہ ور افراد کا قابل اعتماد پارٹنر بننا۔</p></div><div class="info custom-block github-alert"><p class="custom-block-title">ہماری مشن</p><p>منتقلی اور کاروباری قیام کے عمل کو آسان بنانا، اپنے کلائنٹس کو ترقی اور کامیابی پر توجہ دینے کے قابل بنانا۔</p></div><h3 id="کمپنی-کی-حکمت-عملی" tabindex="-1">کمپنی کی حکمت عملی <a class="header-anchor" href="#کمپنی-کی-حکمت-عملی" aria-label="Permalink to &quot;کمپنی کی حکمت عملی&quot;">​</a></h3><ul><li><strong>کلائنٹ مرکزی نقطہ نظر</strong>: ہم ہر کلائنٹ کی مخصوص ضروریات اور اہداف کے مطابق حل فراہم کرتے ہیں، کاروباری تبدیلی کو ہموار بناتے ہیں۔</li><li><strong>عملیاتی برتری</strong>: مقامی مہارت اور موثر طریقہ کار کا استعمال کرتے ہوئے، ہم کلائنٹس کو متحدہ عرب امارات کے کاروباری ماحول کی پیچیدگیوں سے نمٹنے میں مدد کرتے ہیں، وقت اور محنت کو کم کرتے ہیں۔</li><li><strong>پائیدار ترقی</strong>: ہم مستقل، اعلی معیار کی خدمات فراہم کرکے اپنے کلائنٹس کے ساتھ طویل مدتی تعلقات قائم کرنے پر توجہ دیتے ہیں جو کامیابی اور ترقی کو فروغ دیتی ہیں۔</li></ul><h3 id="ہماری-خدمات" tabindex="-1">ہماری خدمات <a class="header-anchor" href="#ہماری-خدمات" aria-label="Permalink to &quot;ہماری خدمات&quot;">​</a></h3><ul><li><strong>کاروباری منتقلی</strong>: متحدہ عرب امارات میں آپ کا کاروبار قائم کرنے میں ماہرانہ مدد۔</li><li><strong>مشاورت</strong>: ضروری دستاویزات حاصل کرنے کے لیے پیشہ ورانہ معاونت۔</li><li><strong>کاروباری معاونت</strong>: آپ کے کاروبار کی کامیابی اور ترقی میں مدد کے لیے جاری عملیاتی معاونت۔</li></ul><div class="important custom-block github-alert"><p class="custom-block-title">ہمیں کیوں منتخب کریں؟</p><p>علم رکھنے والے پیشہ ور افراد کی ٹیم اور ذاتی خدمات کے لیے عزم کے ساتھ، ہم کلائنٹس کے لیے ہموار اور موثر تجربہ یقینی بناتے ہیں، جو انہیں سب سے اہم چیز پر توجہ دینے کی اجازت دیتا ہے – متحدہ عرب امارات میں اپنے کاروبار کو بڑھانا۔</p></div><hr><p><strong>Anastasia Khurtina</strong><br> ڈائریکٹر</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("i18n/ur/resources/about.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const about = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  about as default
};
