import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Đơn Giản Hóa Việc Thành Lập và Phát Triển Kinh Doanh tại UAE","description":"","frontmatter":{"head":[["meta",{"name":"robots","content":"noindex"}]]},"headers":[],"params":{},"relativePath":"vi/resources/about.md","filePath":"i18n/vi/resources/about.md","lastUpdated":1742883140000}');
const _sfc_main = { name: "vi/resources/about.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="đon-gian-hoa-viec-thanh-lap-va-phat-trien-kinh-doanh-tai-uae" tabindex="-1">Đơn Giản Hóa Việc Thành Lập và Phát Triển Kinh Doanh tại UAE <a class="header-anchor" href="#đon-gian-hoa-viec-thanh-lap-va-phat-trien-kinh-doanh-tai-uae" aria-label="Permalink to &quot;Đơn Giản Hóa Việc Thành Lập và Phát Triển Kinh Doanh tại UAE&quot;">​</a></h1><p>GOLDEN FISH cung cấp hỗ trợ toàn diện cho các doanh nghiệp và chuyên gia đang tìm cách thành lập hoặc mở rộng sự hiện diện của họ tại UAE. Sứ mệnh của chúng tôi là đơn giản hóa các quy trình phức tạp về di dời, tuân thủ, tư vấn kinh doanh và quản lý liên tục, đảm bảo trải nghiệm suôn sẻ và hiệu quả cho khách hàng.</p><div class="info custom-block github-alert"><p class="custom-block-title">Tầm Nhìn của Chúng Tôi</p><p>Trở thành đối tác đáng tin cậy cho các doanh nghiệp và chuyên gia muốn thiết lập sự hiện diện thành công tại UAE bằng cách cung cấp hướng dẫn chuyên môn và hỗ trợ đáng tin cậy.</p></div><div class="info custom-block github-alert"><p class="custom-block-title">Sứ Mệnh của Chúng Tôi</p><p>Đơn giản hóa quy trình di dời và thành lập doanh nghiệp, trao quyền cho khách hàng tập trung vào phát triển và thành công.</p></div><h3 id="chien-luoc-cong-ty" tabindex="-1">Chiến Lược Công Ty <a class="header-anchor" href="#chien-luoc-cong-ty" aria-label="Permalink to &quot;Chiến Lược Công Ty&quot;">​</a></h3><ul><li><strong>Tiếp Cận Lấy Khách Hàng Làm Trung Tâm</strong>: Chúng tôi cung cấp giải pháp tùy chỉnh phù hợp với nhu cầu và mục tiêu cụ thể của từng khách hàng, đảm bảo quá trình chuyển đổi kinh doanh suôn sẻ.</li><li><strong>Xuất Sắc trong Hoạt Động</strong>: Bằng cách tận dụng chuyên môn địa phương và quy trình hiệu quả, chúng tôi giúp khách hàng vượt qua những phức tạp của môi trường kinh doanh UAE, giảm thiểu thời gian và công sức.</li><li><strong>Tăng Trưởng Bền Vững</strong>: Chúng tôi tập trung xây dựng mối quan hệ lâu dài với khách hàng bằng cách cung cấp dịch vụ chất lượng cao, nhất quán thúc đẩy thành công và phát triển.</li></ul><h3 id="dich-vu-cua-chung-toi" tabindex="-1">Dịch Vụ của Chúng Tôi <a class="header-anchor" href="#dich-vu-cua-chung-toi" aria-label="Permalink to &quot;Dịch Vụ của Chúng Tôi&quot;">​</a></h3><ul><li><strong>Di Dời Doanh Nghiệp</strong>: Hỗ trợ chuyên môn trong việc thành lập doanh nghiệp tại UAE.</li><li><strong>Tư Vấn</strong>: Hỗ trợ chuyên nghiệp trong việc có được các tài liệu cần thiết.</li><li><strong>Hỗ Trợ Kinh Doanh</strong>: Hỗ trợ hoạt động liên tục để giúp doanh nghiệp của bạn thành công và phát triển.</li></ul><div class="important custom-block github-alert"><p class="custom-block-title">Tại Sao Chọn Chúng Tôi?</p><p>Với đội ngũ chuyên gia am hiểu và cam kết cung cấp dịch vụ cá nhân hóa, chúng tôi đảm bảo trải nghiệm suôn sẻ và hiệu quả cho khách hàng, cho phép họ tập trung vào điều quan trọng nhất – phát triển doanh nghiệp tại UAE.</p></div><hr><p><strong>Anastasia Khurtina</strong><br> Giám đốc</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("i18n/vi/resources/about.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const about = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  about as default
};
