import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"2025年阿联酋UBO登记指南","description":"阿联酋最终受益所有权要求专家指南。全面概述法规、合规和报告义务。","frontmatter":{"title":"2025年阿联酋UBO登记指南","description":"阿联酋最终受益所有权要求专家指南。全面概述法规、合规和报告义务。","head":[["meta",{"name":"robots","content":"noindex"}]]},"headers":[],"params":{},"relativePath":"zh/uae-business/company-registration/ubo.md","filePath":"i18n/zh/uae-business/company-registration/ubo.md","lastUpdated":1742883140000}');
const _sfc_main = { name: "zh/uae-business/company-registration/ubo.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="_2025年阿联酋最终受益所有权-ubo-完整指南" tabindex="-1">2025年阿联酋最终受益所有权(UBO)完整指南 <a class="header-anchor" href="#_2025年阿联酋最终受益所有权-ubo-完整指南" aria-label="Permalink to &quot;2025年阿联酋最终受益所有权(UBO)完整指南&quot;">​</a></h1><p>阿联酋政府于2020年8月推出新法规，要求在阿联酋注册和获得许可的公司维护并提交以下登记册：</p><ul><li><strong>最终受益所有人(UBO或实际受益人)</strong>：识别最终拥有或控制公司的个人，帮助防止公司被用于非法活动。</li><li><strong>股东</strong>：记录公司投资者之间的所有权结构和股权分配。</li><li><strong>名义董事</strong>：确保对代表他人管理公司的个人保持透明。</li></ul><p>该立法的引入目的是：</p><ul><li><strong>打击避税和犯罪活动</strong>，通过确保了解公司的真实所有者，降低被用于非法目的的风险。</li><li><strong>为阿联酋商业部门提供更大的透明度</strong>，通过明确所有权结构，有助于培养信任和合规。</li></ul><h2 id="什么是最终受益人-ubo" tabindex="-1">什么是最终受益人（UBO）？ <a class="header-anchor" href="#什么是最终受益人-ubo" aria-label="Permalink to &quot;什么是最终受益人（UBO）？&quot;">​</a></h2><ul><li><strong>UBO</strong>是直接或间接（包括通过其他实体）拥有或控制公司至少25%股份的自然人。一家公司可以有多个UBO。</li><li>如果无法确定这样的人，那么自然对公司行使控制权的人为<strong>UBO</strong>。</li><li>如果以上都不存在，则公司的<strong>高级管理人员</strong>为实际受益人。</li></ul><h2 id="这些新规定适用于哪些阿联酋公司" tabindex="-1">这些新规定适用于哪些阿联酋公司？ <a class="header-anchor" href="#这些新规定适用于哪些阿联酋公司" aria-label="Permalink to &quot;这些新规定适用于哪些阿联酋公司？&quot;">​</a></h2><ul><li><p><strong>所有</strong>：</p><ul><li>Mainland 公司</li><li>Commercial free zone 公司</li><li>Offshore 公司</li></ul></li><li><p><strong>例外</strong>：</p><ul><li><strong>在阿联酋金融自由区成立的公司</strong>（Abu Dhabi Global Market (ADGM) 和 Dubai International Financial Centre (DIFC)）：这些区域有自己的监管框架，确保符合国际标准。</li><li><strong>由联邦或地方政府直接或间接全资拥有的公司及其子公司</strong>：这些实体通常因其公共所有权和已有的监督水平而获得豁免。</li></ul></li></ul><h2 id="阿联酋公司需要保持哪些登记册" tabindex="-1">阿联酋公司需要保持哪些登记册？ <a class="header-anchor" href="#阿联酋公司需要保持哪些登记册" aria-label="Permalink to &quot;阿联酋公司需要保持哪些登记册？&quot;">​</a></h2><p>公司必须保持：</p><ul><li><strong>实益所有人登记册</strong></li><li><strong>股东或合伙人登记册</strong></li><li><strong>名义董事登记册</strong></li></ul><h2 id="这些登记册应包含哪些信息" tabindex="-1">这些登记册应包含哪些信息？ <a class="header-anchor" href="#这些登记册应包含哪些信息" aria-label="Permalink to &quot;这些登记册应包含哪些信息？&quot;">​</a></h2><ul><li><p><strong>登记册</strong>应包含：</p><ul><li>姓名</li><li>国籍</li><li>护照详细信息</li><li>出生日期和地点</li><li>地址</li><li>个人成为 UBO 的日期和/或不再作为自然受益人的日期</li></ul></li><li><p><strong>股东登记册</strong>应包含：</p><ul><li>每位股东持有的股份数量</li><li>股份的投票权</li><li>获得股份的日期</li><li>所有相关方的信息</li></ul></li><li><p>公司还需要：</p><ul><li><strong>委任并披露</strong>一名居住在 UAE 的自然人（称为授权代理人）的详细信息，该人被授权披露根据决议要求的公司数据和信息。</li><li>在信息发生变更或修改后的15天内<strong>通知登记官</strong>任何变更或修改。</li></ul></li><li><p><strong>登记册必须</strong>：</p><ul><li>在公司存续期间以及公司关闭后五年内保持维护。</li><li>由登记官<strong>保密</strong>：保密性对于保护敏感的公司信息至关重要，确保监管过程中的信任，减少滥用或未经授权访问的风险。</li></ul></li></ul><h2 id="如果公司未能满足这些要求会发生什么" tabindex="-1">如果公司未能满足这些要求会发生什么？ <a class="header-anchor" href="#如果公司未能满足这些要求会发生什么" aria-label="Permalink to &quot;如果公司未能满足这些要求会发生什么？&quot;">​</a></h2><ul><li>可能会对实体施以<strong>制裁和/或行政处罚</strong>。</li><li>阿联酋经济部尚未公布行政处罚清单。</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("i18n/zh/uae-business/company-registration/ubo.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const ubo = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  ubo as default
};
